### ISSUE TITLE
Few question about the paper

### ISSUE THREAD

**Issue by froggyis** [sstocksieker/DAIR#1]
Hi, first I would like to thank you for sharing the code it's really helpful to understand the detail behind the paper, but I still have some question that bother me. I am not sure whether this is the right place to post my issuse, if it's not please tell me and I will remove the post.

**Q1**. From DAIR_Application.md I am not sure which dataset you are using. I know you have stated that the dataset comes form dataset : [http://www2.math.uconn.edu/~valdez/data.html](http://www2.math.uconn.edu/~valdez/data.html). but the code just show the initialization then jump to Analysis part, which I try to reproduce the result on my machine it tells me base0 doesn't exist.

I am not familar with R, so it might just be a simple question.

---

**Q2**. In Weighted Resampling(RA) algorithm block from DAIR_Application.md
![image](https://user-images.githubusercontent.com/34128761/225224620-d5bb512a-5e69-4d99-a58c-b30a49c1706a.png)
which is the kernel part from the paper (my personal perspective) 
![image](https://user-images.githubusercontent.com/34128761/225224815-95e622a3-2fe1-4fbe-9b46-2972207ed087.png)
I am not sure whether the X comes from which features? if the data has multiple dimension let say 5 features(dimenstion) which feature am I going to use, from my perspective I think it should be 5? but in the code it seems that you choose a feature to formulate the target density function.

---
**Q3**. I am trying to reproduce the result using Python. it seems that two main function need to map to python, [density()](https://www.rdocumentation.org/packages/stats/versions/3.6.2/topics/density) and [approx()](https://www.math.ucla.edu/~anderson/rw1001/library/base/html/approxfun.html), which from R documentation.

I think the closet function from Python is [scipy.stats.gaussian_kde](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html) and [scipy.interpolate.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html). I am not sure whether these two pair function are equivalent(I know the default parameter may be totally different. For example, density() in R the bw = "nrd0", however in stats.gaussian_kde, the bw defualt is 0.2, so if the parameters are the same whether the function are equivalent) please give me some hint to understand it.

Lastly, thanks for sharing the code and paper.

**Comment by sstocksieker** [comment]
Thank you for your message and glad to know that you are following my work :)
I answer you below, point by point, don't hesitate to contact me if you need precision.

Q1 : Yes I’m really sorry, there were some cells not displayed (unintentionally). The scripts are updated and everything is available. Typically, you can see that base0 represents the database cited in source.

Q2 : Absolutely, I used only one variable in my application. If you have covariates of dimension 5 (so 5 covariates) you must have a target density of dimension 5 too if these 5 covariates are the target. 
If you have a target density of dimension 1 (for one covariate only) then you have to set the covariate of interest in the function. The 4 other covariates will then be naturally generated as the Y.

Q3 : According to my research (some details below), you can replace "density" by "scipy.stats.gaussian_kde" with the parameter bw_method = 'silverman’.  You can replace "approx" by "numpy.interp"
_

> bw.nrd0 implements a rule-of-thumb for choosing the bandwidth of a Gaussian kernel density estimator. It defaults to 0.9 times the minimum of the standard deviation and the interquartile range divided by 1.34 times the sample size to the negative one-fifth power (= Silverman's ‘rule of thumb’, Silverman (1986, page 48, eqn (3.31))) unless the quartiles coincide when a positive result will be guaranteed.
> scipy.stats.gaussian_kde
> : bw_methodstr, scalar or callable, optional
> The method used to calculate the estimator bandwidth. This can be ‘scott’, ‘silverman’, a scalar constant or a callable. If a scalar, this will be used directly as kde.factor. If a callable, it should take a [gaussian_kde](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.gaussian_kde.html#scipy.stats.gaussian_kde) instance as only parameter and return a scalar. If None (default), ‘scott’ is used. See Notes for more details.
> 
> 
> approxfun: Interpolation Functions : Return a list of points which linearly interpolate given data points
> numpy.interp(x, xp, fp, left=None, right=None, period=None)[[source]]
> One-dimensional linear interpolation for monotonically increasing sample points._

_

**Comment by froggyis** [comment]
thanks for reply, I need some time to digest the messages
